api_hash: "7dd9974c713787410beae4a295cc1e2d"
api_id: 27885485
chat_id: -1001900357579
download_directory: "downloads"
file_formats:
  audio:
  - all
  document:
  - all
  video:
  - all
ids_to_retry: {}
last_read_message_id: {}
media_types:
- audio
- photo
- video
- document
- voice
- video_note
phone_number: int("+5577999132829")
